server:
  port: 8083
 
spring:
  application:
    name: API_Gateway
    
  cloud:
    gateway:
      routes:
      - id: ThreatreRegisterService
        uri:
          lb://ThreatreRegisterService
        predicates:
        - PATH=/theatre/**
        
      - id: BookService
        uri:
          lb://BookService
        predicates:
        - PATH=/book/**